### ISSUE TITLE
Feature wish list

### ISSUE THREAD

**Issue by kimdhamilton** [digitalcredentials/designer#1]
* [ ] Reference json schema
* [ ] Validate against json schema
* [ ] Create json schema from json
    - https://jsonschema.net/home
* [ ] Create json ld from json
* [ ] Sign?
* [ ] Create HTML form from json schema / json-ld?
    - https://rjsf-team.github.io/react-jsonschema-form/
    - https://jsonform.github.io/jsonform/playground/index.html?example=schema-basic
* [ ] DnD/upload attachments (rather than manual base64 approach)
* [ ] Generate form from schema builder framework to make our lives easier. [Some options](https://ourcodeworld.com/articles/read/610/top-5-best-drag-and-drop-form-builders-plugins-for-javascript-and-jquery)
* [ ] Generate/preview credential archive files
* [ ] Support generation of templates that can be used in real workflows (i.e. merging in learner data, subsequent signing)

**Comment by dmitrizagidulin** [comment]
Overtaken by events, closing.
