### ISSUE TITLE
Playground Design Considerations

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalcredentials/designer#36]
Audience:

1. Issuers (universities etc) that are deploying an issuer service for use with learner credential wallets.
    - As a member of the institution's IT team, I want to issue an example VC (to get it into the wallet, to test with other verifiers). 
2. Wallet and VC application developers.
   - As a developer of a VC issuing or verifying application (say, a human resources tracking app), I want to check that my verifying library is working correctly by pasting a VC into the playground, and seeing if it verifies.
3. Relying parties / verifiers. (this is not as important, because we'll have a separate Verifier service, for this purpose).

Potential starting codebases:

1. Existing DCC Playground https://github.com/digitalcredentials/playground
2. https://api.did.actor/  (which is at https://github.com/transmute-industries/api.did.actor )
3. Blank screen

**Comment by fields37** [comment]
Should we close this?

**Comment by dmitrizagidulin** [comment]
This is addressed in latest main, closing.
