### ISSUE TITLE
Footer links all messed up

### ISSUE THREAD

**Issue by fields37** [digitalcredentials/designer#47]
The first row of footer links at the bottom of the page do not redirect to the hrefs [given here](https://github.com/digitalcredentials/sandbox/blob/main/src/navigation/Dashboard/Footer.tsx). It is extremely curious because when all of the footer links are combined into one row they work  fine.

**Comment by bmuramatsu** [comment]
That's odd.

You can take these two files and update them for "LCW" -> "DCC Developer
Sandbox" and "App" -> "Site"
https://github.com/digitalcredentials/learner-credential-wallet-site/blob/main/privacy.html
https://github.com/digitalcredentials/learner-credential-wallet-site/blob/main/terms.html

To put real text into those two areas. Privacy will need to get updated
more than Terms, but is ok for now.

**Comment by fields37** [comment]
Terms and conditions and privacy policy pages added in #54
