### ISSUE TITLE
UI Design

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/designer#49]
- Consider using the gray from the footer on https://digitalcredentials.mit.edu/ as the primary color
- Reduce the size of the DCC logo in the header
- Reduce the font size throughout
- Put the icon and Issue and icon and Verify on the same line -- to reduce the use of site chrome, especially on mobile devices (current design takes up 1/3 of iPhone 13 Pro with chrome at the top of the homepage)

**Comment by fields37** [comment]
- [ ] Fix color mismatch in footer between MUI links and react-router-dom links

**Comment by fields37** [comment]
@bmuramatsu Do you want the DCC logo to link to digitalcredentials.mit.edu?

**Comment by bmuramatsu** [comment]
Yes, please.

**Comment by fields37** [comment]
The above changes (except for the DCC logo link) have been made in #56 and are now online. Let me know if you have any further comments on the UI

**Comment by fields37** [comment]
Logo link added in #65
