### ISSUE TITLE
Playground should be responsive

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/designer#59]
Playground doesn't seem to change display as the browser window changes. @dmitrizagidulin  pointed out and requested that a bug be submitted.

**Comment by bmuramatsu** [comment]
Works as I think it should, responsively, for me under Mac Safari Version
14.1.2 (14611.3.10.1.7) and Google Chrome Version 105.0.5195.125 (Official
Build) (x86_64)

Also on an iPad and iPhone.

**Comment by fields37** [comment]
Yeah it's responsive for me on mobile and browser, although I haven't tested extensively across different systems! Could you possibly share a screenshot under the conditions where it wasn't working as expected?

**Comment by bmuramatsu** [comment]
Also works for me on Android 11...

**Comment by kayaelle** [comment]
Strange - when Dmitri and I looked at it together it wasn't. We looked at in in Chrome Version 105.0.5195.125 but also in zoom sharing which could have affected that I guess. Thanks for looking at it. Closing.
