### ISSUE TITLE
Playground page not scrolling after clicking on sign credential

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/designer#60]
Playground page not scrolling after clicking on "sign credential". Discussed with @dmitrizagidulin and he requested that an issue be submitted.

**Comment by bmuramatsu** [comment]
Works as I think it should, scrolling after signing the credential (though
it's not actually signed), for me under Mac Safari Version 14.1.2
(14611.3.10.1.7) and Google Chrome Version 105.0.5195.125 (Official Build)
(x86_64)

**Comment by fields37** [comment]
Working for me as well! Do you know the conditions under which it wasn't scrolling?

**Comment by kayaelle** [comment]
Closing. May have been caused by demonstrating in zoom? Can't replicate any longer.
