### ISSUE TITLE
File upload option

### ISSUE THREAD

**Issue by fields37** [digitalcredentials/designer#62]
Add the ability to upload a JSON file on the issue and verify pages containing the credentials to be signed or verified. Generally model things off of the web verifier file uploader, allow both file select and and drag + drop. Check that file is JSON?

<img width="521" alt="Screen Shot 2022-10-06 at 5 09 57 PM" src="https://user-images.githubusercontent.com/20584379/194419476-3fd1029a-6658-4e0e-bca2-58eba78d8c8f.png">

**Comment by fields37** [comment]
Additional specifications:
- Allow only .json files
- Upon upload, insert contents of the file into the credential editor

**Comment by fields37** [comment]
Ignoring the cosmetic differences in design between this render and the current website, this is my initial thought for how to integrate the file upload option into the existing design.
**Issue page:**
<img width="970" alt="Screen Shot 2022-10-06 at 5 51 45 PM" src="https://user-images.githubusercontent.com/20584379/194425748-333a6e4c-7a42-4031-997a-25a3332fb481.png">
**Verify Page:**
<img width="709" alt="Screen Shot 2022-10-06 at 5 51 53 PM" src="https://user-images.githubusercontent.com/20584379/194425851-8948b210-f9b2-47f7-8378-74e706149418.png">
**Verify page narrow:**
<img width="395" alt="Screen Shot 2022-10-06 at 5 52 13 PM" src="https://user-images.githubusercontent.com/20584379/194425913-1e6b49d4-d7bc-4d49-878e-e103e09264b6.png">

**Comment by bmuramatsu** [comment]
I'd go either above or below the paste field. On VerifierPlus we did below,
see https://web-verifier-plus.vercel.app. Probably reduce the height of the
paste field a few lines.

Brandon

**Comment by fields37** [comment]
Yep, planning to switch to below text box instead of above

**Comment by fields37** [comment]
First rev implemented in #66
