### ISSUE TITLE
License review

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/designer#64]
If you're using sub-libraries or code, we need to make sure we can share this back as MIT License. Can you please compile licenses for sub-libraries so we can submit this to MIT Technology Licensing for review.

**Comment by fields37** [comment]
Is this an adequate format?
- [Material UI](https://github.com/mui/material-ui) - [MIT License](https://github.com/mui/material-ui/blob/master/LICENSE)
- [React Ace](https://github.com/securingsincity/react-ace) - [MIT License](https://github.com/securingsincity/react-ace/blob/main/LICENSE)
- [Github Action to deploy to Github Pages](https://github.com/crazy-max/ghaction-github-pages) - [MIT License](https://github.com/crazy-max/ghaction-github-pages/blob/dev/LICENSE)
- [Single Page Apps for Github Pages](https://github.com/rafgraph/spa-github-pages) - [MIT License](https://github.com/rafgraph/spa-github-pages/blob/gh-pages/LICENSE)
- [Create-react-app](https://github.com/facebook/create-react-app) - [MIT License](https://github.com/facebook/create-react-app/blob/main/LICENSE)
- [vpqr](https://github.com/digitalbazaar/vpqr) - [BSD-3-Clause License](https://github.com/digitalbazaar/vpqr/blob/main/LICENSE)
- [jsonId-document-loader](https://github.com/transmute-industries/jsonld-document-loader) - [Unlicense License](https://github.com/transmute-industries/jsonld-document-loader/blob/master/LICENSE)
- [React router](https://github.com/remix-run/react-router) -- [MIT License](https://github.com/remix-run/react-router/blob/main/LICENSE.md)
- [mui-file-dropzone](https://github.com/Deckstar/mui-file-dropzone) - [MIT License](https://github.com/Deckstar/mui-file-dropzone/blob/master/LICENSE)

**Comment by bmuramatsu** [comment]
Can you please add the license to the bullet with a link to the license file if it exists.Can you also please dig into React Ace, there wasn’t a license at first look.On Oct 21, 2022, at 9:26 AM, fields37 ***@***.***> wrote:﻿
Is this an adequate format?

Material UI
React Ace
Github Action to deploy to Github Pages
Single Page Apps for Github Pages
StackOverflow response for using HTML anchors with react-router
Code snippet for MUI "Copy to Clipboard" button
Create-react-app
Code snippet for dynamic page titles within react-router
vpqr
jsonId-document-loader
React router

**Comment by bmuramatsu** [comment]
Nevermind on React Ace, there is a MIT license.

Please list the licenses and link to their license file if it exists.

Thanks.

**Comment by fields37** [comment]
Hi Brandon, I've updated my original comment with a link to the licenses.

**Comment by bmuramatsu** [comment]
Thanks!

**Comment by bmuramatsu** [comment]
Thanks! (sorry it's taken a long time to get back to this!)

Brandon

**Comment by kayaelle** [comment]
@bmuramatsu - can this issue be closed?

**Comment by bmuramatsu** [comment]
Submitted and received ok by MIT TLO to license with MIT license.
