### ISSUE TITLE
QR Code upload of unsigned/signed credentials

### ISSUE THREAD

**Issue by fields37** [digitalcredentials/designer#68]
Add a feature on both the "Issue" and "Verify" pages that allows uploads of json credential files into the editor through scanning a QR code. Should work with cameras on smartphone and computers. Credentials can be encoded in a QR code in three ways:
1. A link pointing to a web-hosted JSON file
2. Raw text parsable into JSON
3. Text-encoded binary

**Comment by fields37** [comment]
This is my initial proposal of how to arrange the interface around the three input options of direct text input, file upload, and QR code scan.
Issue screen: <img width="958" alt="Screen Shot 2022-10-31 at 11 27 45 PM" src="https://user-images.githubusercontent.com/20584379/199154039-6db28669-70a6-4cd8-a2e5-56d57b5715aa.png">
Verify screen: <img width="807" alt="Screen Shot 2022-10-31 at 11 27 58 PM" src="https://user-images.githubusercontent.com/20584379/199154082-c4a7e5fc-2434-4543-895b-b3d92cea01b7.png">

**Comment by fields37** [comment]
@dmitrizagidulin @bmuramatsu The thought behind this proposed layout is that the file upload and QR code upload have equal weight as input options, and so should be balanced in size and style. Typing/pasting into the text editor is an equally valid input method, but all three input modes will result in the credential text showing up in the editor window, so overall that area of the screen should take up more space (on top of a text editor needing more space than buttons). For the same reason I think it makes sense for the editor to appear below the upload/QR options, as the results of those options will appear in the editor and it therefore flows with the overall downward movement through the page as you progress through the issuing process.

**Comment by bmuramatsu** [comment]
We're also trying to maintain consistency with LCW. And I believe we
decided to do Scan QR Code, Paste URL or JSON and File upload in that
order. Dmitri can confirm. And what happens for narrow media widths?

**Comment by fields37** [comment]
On narrow media widths I think the two input method areas will need to stack. I can try to make them both less tall by sticking the icon to the left of the text rather than below.

This is just my initial UX instinct, I will defer to you guys' preference. I'm not able to get LCW to run on my phone so can't see the layout, but at least looking at the WebVerifier, there is a functional difference in the input section between the WebVerifier and Sandbox. That is, the text input doesn't really function as a JSON editor, and it doesn't allow you to view/edit the credentials uploaded through the other methods. In the sandbox, it does, which makes the editor more of a functional focal point.
