### ISSUE TITLE
Add Open Badges Example

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/designer#83]
We should put some examples in the sandbox of Open Badges. 

related (and maybe useful for this) @jchartrand has a script that generates credentials. Should we plug it into the sandbox?

**Comment by alexfigtree** [comment]
No longer needed, closing

**Comment by alexfigtree** [comment]
https://github.com/digitalcredentials/sandbox/issues/58 taking priority over this one, hence closing
